# Student Result Predictio (Pass/Fail)

In [95]:
# step 1 : take training data
import pandas as pd
import numpy as np

url = "https://raw.githubusercontent.com/itsluckysharma01/Datasets/refs/heads/main/student-pass-fail-data.csv"


In [96]:
# Read the csv file using read_csv method and save in  dataframe df
df = pd.read_csv(url)
df

Self_Study_Daily  Tutorials_Monthly  Pass_Or_Fail
0                   7                 27             1
1                   2                 43             0
2                   7                 26             1
3                   8                 29             1
4                   3                 42             0
..                ...                ...           ...
995                 6                 22             1
996                 9                 30             1
997                 3                 39             0
998                 7                 25             1
999                 5                 37             0

[1000 rows x 3 columns]

In [97]:
df.describe()

Self_Study_Daily  Tutorials_Monthly  Pass_Or_Fail
count       1000.000000        1000.000000   1000.000000
mean           5.744000          31.230000      0.499000
std            2.121076           5.976355      0.500249
min            0.000000          20.000000      0.000000
25%            4.000000          26.000000      0.000000
50%            6.000000          30.000000      0.000000
75%            7.000000          36.000000      1.000000
max           10.000000          50.000000      1.000000

In [98]:
df.iloc[0,0]

np.int64(7)

In [99]:
df.head()

Self_Study_Daily  Tutorials_Monthly  Pass_Or_Fail
0                 7                 27             1
1                 2                 43             0
2                 7                 26             1
3                 8                 29             1
4                 3                 42             0

Step 2: vertically divide the data into inputs(x) and outputs(y)

In [100]:
df1=df.values
X=df1[0,0:2]
Y=df1[:,2]


In [101]:
Y[:5]

array([1, 0, 1, 1, 0])

Step 3 : choose appropriate machine learning algorithm/Model

In [ ]:

from sklearn.linear_model import LinearRegression
model = LinearRegression()

Fit the data into the selected model

In [108]:
# Use all rows and the first two columns as features, and the third column as target
X_train = df1[:, 0:2]
Y_train = df1[:, 2]
model.fit(X_train, Y_train)

LinearRegression()

Step 5 : Predict  the result with use input

In [109]:
model.predict([[7,27]])

array([0.7907862])

In [ ]:
# rr = model.predict([[7,27]])


array([0.7907862])

In [ ]:
# print(type(rr), str(rr[0]*100)+ "%")

<class 'numpy.ndarray'> 79.0786201805112%


In [ ]:
# a= 5
# b=33
# ab = [[a,b]]
# print(type(ab),ab)
# rr = model.predict(ab)
# print(str(round(rr[0],2)*100)+ "%")

In [113]:
round(27.19202102,2)

27.19

In [114]:
model.predict([[2,60]])

array([-0.93897404])

In [115]:
model.predict([[2,43]])

array([-0.34127902])

In [116]:
model.predict([[2,35]])

array([-0.06001077])

# Final Go

* step 1 : take training data

In [120]:
# step 1 : take training data
import pandas as pd
import numpy as np

url = "https://raw.githubusercontent.com/itsluckysharma01/Datasets/refs/heads/main/student-pass-fail-data.csv"
df = pd.read_csv(url)

In [121]:
df

Self_Study_Daily  Tutorials_Monthly  Pass_Or_Fail
0                   7                 27             1
1                   2                 43             0
2                   7                 26             1
3                   8                 29             1
4                   3                 42             0
..                ...                ...           ...
995                 6                 22             1
996                 9                 30             1
997                 3                 39             0
998                 7                 25             1
999                 5                 37             0

[1000 rows x 3 columns]

* Step 2 : vertically divide the data into inputs(x) and outputs(y)

In [122]:
df1 = df.values
X=df1[:,0:2]
Y=df1[:,2]
print(X[:5,:],Y[:5])

[[ 7 27]
 [ 2 43]
 [ 7 26]
 [ 8 29]
 [ 3 42]] [1 0 1 1 0]


In [123]:
#step 3 -  choose appropriate Machine Learning Algo/model
from sklearn.linear_model import LinearRegression
model = LinearRegression()
#step 4 - fit the data into the selected model
model.fit(X,Y)
# Step 5 - Predict the results with user input
a=model.predict([[7,27]])
print(a[0]*100)
# Step 6 - Testing
# Step 7 - Deployment

79.0786201805112


In [124]:
a=model.predict([[4,30]])
print(a[0]*100)

34.359337215017426


In [125]:
# print ("{.2f}".format(a))
print( "%.2f"%(a*100))

34.36


C:\Users\PANDIT JI\AppData\Local\Temp\ipykernel_15080\4104727390.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  print( "%.2f"%(a*100))


# Diabetes Prediction

In [126]:
import pandas as pd
url  ="https://raw.githubusercontent.com/itsluckysharma01/Datasets/refs/heads/main/diabetes1.csv"
df = pd.read_csv(url)

In [127]:
df.shape
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [128]:
df.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [129]:
X = df[df.columns[:8]]
Y = df[df.columns[8]]
print (df.shape , X.shape, Y.shape)

(768, 9) (768, 8) (768,)


In [130]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

model.fit(X , Y)

C:\Users\PANDIT JI\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [131]:
model.predict( [[6	,148 ,	72, 	35, 	0, 	33.6,	0.627,	50	]])

C:\Users\PANDIT JI\AppData\Roaming\Python\Python311\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([1])

In [132]:
model.predict( [[1,	85,	66,	29,	0	,26.6,	0.351	,31 ]])

C:\Users\PANDIT JI\AppData\Roaming\Python\Python311\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([0])

In [133]:
url  ="https://raw.githubusercontent.com/itsluckysharma01/Datasets/refs/heads/main/diabetes1.csv"
df = pd.read_csv(url)
X = df[df.columns[:8]]
Y = df[df.columns[8]]

from sklearn.linear_model import LinearRegression
model = LinearRegression()

model.fit(X , Y)
model.predict( [[1,	85,	66,	29,	0	,26.6,	0.351	,31 ]])

C:\Users\PANDIT JI\AppData\Roaming\Python\Python311\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([0.00573265])

In [134]:
model.predict( [[6	,148 ,	72, 	35, 	0, 	33.6,	0.627,	50	]])

C:\Users\PANDIT JI\AppData\Roaming\Python\Python311\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([0.65175729])

# Sentiment analysis

In [135]:
# Step 1 – Training data
# training data should be labeled for supervised learning
train = [("Great place to be when you are in chandigarh.", "pos"),
         ("The place was being renovated when I visited so the seating was limited.", "neg"),
         ("Loved the ambience, loved the food", "pos"),
         ("The food is delicious but not over the top.", "neg"),
         ("Service - Little slow, probably because too many people.", "neg"),
         ("The place is not easy to locate", "neg"),
         ("Mushroom fried rice was spicy", "pos") ]

In [136]:
import nltk
from nltk.tokenize import word_tokenize
nltk.download('punkt')

[nltk_data] Downloading package punkt to C:\Users\PANDIT
[nltk_data]     JI\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [137]:
# testing to understand the logic in step 2
dictionary = set(word.lower() for passage in train for word in word_tokenize(passage[0]))
# dictionary

In [138]:
# Step 3
t = [({word: (word in word_tokenize(x[0])) for word in dictionary}, x[1]) for x in train]

In [139]:
# Step 4 – the classifier is trained with sample data
classifier = nltk.NaiveBayesClassifier.train(t)
classifier

In [140]:
#prepare a input to test the model for response

test_data = "The food is delicious we loved it"
test_data_features = {word.lower(): (word in word_tokenize(test_data.lower()))
                      for word in dictionary}
print (classifier.classify(test_data_features))

pos


In [141]:
test_data = "place was not accessible"
test_data_features = {word.lower(): (word in word_tokenize(test_data.lower()))
                      for word in dictionary}
print (classifier.classify(test_data_features))

neg
